package source

import (
	"github.com/jung-kurt/gofpdf"
	"io"
	"log"
	"github.com/edustor/gen/bindata"
	"github.com/satori/go.uuid"
	"fmt"
	"strings"
	"time"
)

func GenPdf(writter io.Writer, pageCount int) (err error) {
	pdf := gofpdf.New("P", "mm", "A4", "")

	for i := 0; i < pageCount; i++ {
		pdf.AddPage()

		pageId := uuid.NewV4().String()
		uri := fmt.Sprintf("edustor://d/%s", pageId)
		qr, err := GenQR(uri)
		if err != nil {
			panic(err)
		}

		_idParts := strings.Split(pageId, "-")
		_idTail := _idParts[len(_idParts)-1]

		topId := fmt.Sprintf("#%s  #__________", _idTail[8:12])
		bottomId := fmt.Sprintf("#%s-%s-%s", _idTail[0:4], _idTail[4:8], _idTail[8:12])

		drawPage(pdf, topId, bottomId, qr)
	}

	err = pdf.Output(writter)
	return err
}

func drawPage(pdf *gofpdf.Fpdf, topId string, bottomId string, qr []byte) {
	fontJson, err := bindata.Asset("fonts/Proxima Nova Thin.json")
	if err != nil {
		log.Panic(err)
	}
	fontZ, err := bindata.Asset("fonts/Proxima Nova Thin.z")
	if err != nil {
		log.Panic(err)
	}
	pdf.AddFontFromBytes("Proxima Nova", "Thin", fontJson, fontZ)
	pdf.SetFont("Proxima Nova", "Thin", 11)
	pdf.SetMargins(0, 0, 0)
	pdf.SetAutoPageBreak(false, 0)

	pdf.SetLineWidth(0.01)
	pdf.SetDrawColor(128, 128, 128)

	pageWidth, pageHeight := pdf.GetPageSize()

	const X_CELLS = 40
	const Y_CELLS = 56

	xMargin := (pageWidth - (X_CELLS * 5)) / 2
	yMargin := (pageHeight - (Y_CELLS * 5)) / 2

	xMin, xMax := xMargin, pageWidth-xMargin
	yMin, yMax := yMargin, pageHeight-yMargin

	// Grid
	for x := xMin; x <= xMax; x += 5 {
		pdf.Line(x, yMin, x, yMax)
	}

	for y := yMin; y <= yMax; y += 5 {
		pdf.Line(xMin, y, xMax, y)
	}

	// Print header
	pdf.SetY(yMin - 2.8)
	pdf.SetX(xMin - 1)
	pdf.CellFormat(1, 1, "Edustor Alpha", "", 0, "", false, 0, "")

	pdf.SetX(xMax - 1 - pdf.GetStringWidth(topId))
	pdf.CellFormat(1, 1, topId, "", 0, "", false, 0, "")

	// Print footer
	pdf.SetY(yMax + 2)
	pdf.SetX(xMin - 1.4)
	pdf.SetFontSize(8)
	now := time.Now()
	//TODO: Fix B appearing before © after render
	copyrightStr := fmt.Sprintf("Generated by Edustor PDFGen on %v. ©Edustor Project. Dmitry Romanov, %v",
		now.Format(time.UnixDate), now.Year())
	pdf.CellFormat(1, 1, copyrightStr, "", 0, "", false, 0, "")
}
